export const USE_HUSTLE = "USE_HUSTLE"
export const USE_PASSIVE_HUSTLE = "USE_PASSIVE_HUSTLE"
export const INITIALIZE_PASSIVE_INTERVAL = "INITIALIZE_PASSIVE_INTERVAL"
export const BUY_HUSTLE = "BUY_HUSTLE"
export const BUY_HUSTLER = "BUY_HUSTLER"
export const BUY_SKIN = "BUY_SKIN"

